### ISSUE TITLE
AssertionError at /graphql

### ISSUE THREAD

**Issue by nioperas06** [howtographql/graphene#3]
CreateUser fields must be a mapping (dict / OrderedDict) with field names as keys or a function which returns such a mapping.

**Comment by damufo** [comment]
Hello:
https://www.howtographql.com/graphql-python/2-queries/


Internal Server Error: /graphql/
Traceback (most recent call last):
  File "/home/www-data/django-api/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/www-data/django-api/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/www-data/django-api/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www-data/django-api/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/www-data/django-api/lib/python3.5/site-packages/django/views/generic/base.py", line 63, in view
    self = cls(**initkwargs)
  File "/home/www-data/django-api/lib/python3.5/site-packages/graphene_django/views.py", line 85, in __init__
    self.schema, GraphQLSchema), 'A Schema is required to be provided to GraphQLView.'
AssertionError: A Schema is required to be provided to GraphQLView.
[15/Nov/2018 08:51:17] "GET /graphql/ HTTP/1.1" 500 70794

Will I do something wrong?
I have to say I do not control much of django.
Thanks
